name: C++ CI Build

on: [push, pull_request]

jobs:
  build:
    name: Build on Linux and macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++ on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Install g++ on macOS
      if: matrix.os == 'macos-latest'
      run: brew install gcc

    - name: Run Makefile
      run: make all
