name: C++ CI Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install g++ on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++

      - name: Install g++ on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gcc

      - name: Build with Makefile
        run: make all

      # Optional: Upload build artifacts
      - name: Upload binaries
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            ./bin/*
            ./build/*
